force-app/main/default/objects/SQX_Nonconformance__c/SQX_Nonconformance__c.object-meta.xml
<CustomObject>
    <label>Nonconformance</label>
    <nameField>
        <displayFormat>NC-{0000000000}</displayFormat>
        <label>Nonconformance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nonconformances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Nonconformance__c/fields/QMS_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>QMS_Reference_Number__c</fullName>
    <label>QMS Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Nonconformance__c/fields/SQX_NC_Reference__c.field-meta.xml
<CustomField>
    <fullName>SQX_NC_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NC Reference</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Nonconformances</relationshipLabel>
    <relationshipName>Nonconformances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
public class CaseTriggerHandler {

    
    public static void creatNonconforanceRecord(List<Case> caseNewList, Map<Id,Case> caseOldMap){
       
        Set<Id> caseIdSet = new Set<Id>();
        List<SQX_Nonconformance__c> sqxNonConfList = new List<SQX_Nonconformance__c>();
         boolean createChildFlag =false;
        
        if(!caseNewList.isEmpty()){
            for(Case objCase : caseNewList){
                if(objCase.Type =='Problem')
                	caseIdSet.add(objCase.Id);
            }
        }
        
        Map<Id,Case> caseMap = new Map<Id,Case>();
        
        if(!caseIdSet.isEmpty()){
            for(Case objCase : [select id,Type, (select Id from Nonconformances__r) from Case where Id IN : caseIdSet]){
                caseMap.put(objCase.Id,objCase);
            }
        }
        
        if(!caseMap.isEmpty()){
            for(Case objCase : caseNewList){
                if(caseMap.containsKey(objCase.Id)){
                    if(caseMap.get(objCase.Id).Nonconformances__r.size() == 0){
                        SQX_Nonconformance__c objSQXNonConf = new SQX_Nonconformance__c();
                        objSQXNonConf.SQX_NC_Reference__c 	  = objCase.Id;
                        objSQXNonConf.Priority__c 		  	  = objCase.Priority;
                        objSQXNonConf.Title__c 			  	  = objCase.Subject;
                        objSQXNonConf.Description__c 	  	  = objCase.Description;
                        objSQXNonConf.QMS_Reference_Number__c = objCase.CaseNumber;
                        createChildFlag = true;
                        
                        sqxNonConfList.add(objSQXNonConf);    
                    }
                    if(caseOldMap!=null && caseMap.get(objCase.Id).Nonconformances__r.size()!=0){ //update
                        SQX_Nonconformance__c objSQXNonConf = new SQX_Nonconformance__c();
                        objSQXNonConf.Id	  = caseMap.get(objCase.Id).Nonconformances__r[0].Id;
                        objSQXNonConf.Priority__c 		  	  = objCase.Priority;
                        objSQXNonConf.Title__c 			  	  = objCase.Subject;
                        objSQXNonConf.Description__c 	  	  = objCase.Description;
                        objSQXNonConf.QMS_Reference_Number__c = objCase.CaseNumber;
                        
                        sqxNonConfList.add(objSQXNonConf);    
                    }
                    
                    
                }
            }
        }
        
        if(!sqxNonConfList.isEmpty()){
            if(caseOldMap == null || createChildFlag){//Insert
            	Database.insert(sqxNonConfList,false);
            }
            else{ //Update
                Database.update(sqxNonConfList,false);
            }
        }
        
        
    }
}